### ISSUE TITLE
How to handle DEB and UCCS?

### ISSUE THREAD

**Issue by laurencelundblade** [thomas-fossati/draft-eat-mt#1]
The first simple and obvious question is what would the type of a UCCS be? There is also the DEB. https://datatracker.ietf.org/doc/html/draft-ietf-rats-eat-12#section-5

If this is to parallel COSE, then I think we'd have:

eat-cwt (eat-cwt+cbor seems redundant; or maybe eat+cbor implies CWT)
eat-jwt (eat-jwt+json seems redundant)
eat-deb+cbor
eat-deb+json
eat-uccs (eat-uccs+cbor seems redundant)
eat-ujcs (eat-ujcs+json seems redundant)

They all follow the EAT semantics and requirements, but they are different forms and encodings.

**Comment by thomas-fossati** [comment]
> The first simple and obvious question is what would the type of a UCCS be? There is also the DEB. https://datatracker.ietf.org/doc/html/draft-ietf-rats-eat-12#section-5
> 
> If this is to parallel COSE, then I think we'd have:
> 
> eat-cwt (eat-cwt+cbor seems redundant; or maybe eat+cbor implies CWT)

I don't think we need to define this: `eat+cbor` should be enough.

> eat-jwt (eat-jwt+json seems redundant)

I don't think we need to define this: `eat+json` should be enough.

> eat-deb+cbor
> eat-uccs (eat-uccs+cbor seems redundant)

I was under the impression (correct me if I'm wrong) that these two are always wrapped in their CBOR tags (601, 602) when they are transported.  If so, they'd be `application/eat+cbor` IMHO.

> eat-ujcs (eat-ujcs+json seems redundant)
> eat-deb+json

Since JSON does not have tagging, the situation here is slightly different from their CBOR equivalent.  Maybe we need to define these.

**Comment by laurencelundblade** [comment]
Don't have a strong opinion here yet.

We could do eat+cbor and then require a CBOR tag to distinguish between CWT, DEB and UCCS (and maybe a future format). Seems workable. There will definitely be a CBOR tag for DEB and UCCS and there is already one for CWT. However EAT, like CWT and COSE do not require use of the tag. The tag's use depends on the context. We could require its use in this context.

However, that is different from what COSE did. They definitely made a separate CoAP ID for each and used the same integer value for CoAP ID as the tag (which is both confusing and convenient to me). https://datatracker.ietf.org/doc/html/rfc8152#section-16.10

Subtypes of eat+json could be distinguished because a JWT is always b64 text (raw b64 text, not a JSON string containing b64 text),a DEB is always a JSON array and a UJCS is always a JSON map, but that seems a bit fragile and inextensible.

I am now leaning a little towards what COSE did because it is a precedent and it clearly solves the problem once and for all for both CBOR and JSON (and future stuff someone might come up with).

This discussion also begs the question of how the type of a submod is identified in EAT. Right now it is tags in CBOR and something else in JSON. https://datatracker.ietf.org/doc/html/draft-ietf-rats-eat-12#section-3.25.1.2

Also see this where I'm using CoAP Content Type for CoSWID in EAT. https://github.com/ietf-rats-wg/eat/pull/179

**Comment by thomas-fossati** [comment]
Having re-read the EAT draft, I think your classification is right.  We need 6 types

| media type | description |
| ---- | ----------- |
| `eat-cwt` | claims map protected using CWT |
| `eat-jwt` | claims map protected using JWT |
| `eat-deb+json` | JSON-encoded DEB |
| `eat-deb+cbor` | CBOR-encoded DEB |
| `eat-ucs+json` | JSON-encoded claims map |
| `eat-ucs+cbor` | CBOR-encoded claims map |

----

Random note: I have just had the realisation that EAT, at its core, is conceptually just a set of attestation-related claims.

In hindsight we should have probably called it ACS (attestation claims set) :-) and define its three different flavours:

* unprotected (ACS-U)
* protected (ACS-P)
* detached (ACS-D)

**Comment by henkbirkholz** [comment]
So UCS+JSON and UCS+CBOR fior the UCS space. Okay. Maybe there is the next gen acronym derivable by that table. Will take this under consideration at the "other end".

**Comment by thomas-fossati** [comment]
Brain dump pic of the EAT machinery

![eat](https://user-images.githubusercontent.com/9195842/168090149-0af9d254-6f1d-47dd-9ecc-f420d5aba592.png)

**Comment by laurencelundblade** [comment]
<img width="1261" alt="Screen Shot 2022-05-12 at 7 52 09 PM" src="https://user-images.githubusercontent.com/7951515/168195635-e625cc7a-fe7a-4899-a5a9-ca935f2ced9d.png">

**Comment by laurencelundblade** [comment]
Dark blue are actual serialize tokens.

Light blue with rounded corners are processes that do something.

The other are things described in CDDL.

Inside the simplest DEB is 1) a Claims-Set and 2) a Nested-Token like a CWT. That Nested-Token/CWT has a Claims-Set that has a submodule that is a Detached-Digest which is the hash of 1).

**Comment by laurencelundblade** [comment]
I would not think of a CWT as a crypto-wrapped UCCS. A UCCS might be a tag (601 is what is proposed) and that wouldn't be legal inside a CWT.

**Comment by thomas-fossati** [comment]
Thank you!  I have added UJCS, JWT and a legenda, and saved it to [misc/](https://github.com/thomas-fossati/draft-eat-mt/blob/main/misc/EAT-pieces.pdf).

(There is the raw OmniGraffle in case you want to edit further.)

**Comment by laurencelundblade** [comment]
To be completely accurate, there are both CBOR and JSON versions of a DEB. The CDDL for them is same, but they do encode differently.

There should probably be a note about the "Tag" process for UCCS or someone is going to squawk: "Tag" is minimal and either produces a Tagged Claims-Set or an Untagged Claims-Set.

Glad to have this. I think this will be helpful.

**Comment by thomas-fossati** [comment]
> To be completely accurate, there are both CBOR and JSON versions of a DEB. The CDDL for them is same, but they do encode differently.

Cool, will split DEB into two.

> There should probably be a note about the "Tag" process for UCCS or someone is going to squawk: "Tag" is minimal and either produces a Tagged Claims-Set or an Untagged Claims-Set.

Lazy question: are Tagged Claims-Set and Untagged Claims-Set both UCCS?  If so, `Tag` could be an optional processing step between the `Claims-Set` and `UCCS` boxes.

> Glad to have this. I think this will be helpful.

It is already for me.  I'm going to make it into an SVG that can be included in the draft to provide a rationale for the media types.

**Comment by laurencelundblade** [comment]
Any of the serialization formats, DEB, COSE or UCCS can be tagged or not tagged.

An untagged UCCS is in serialized format no different than a Claims-Set.

Formally, there is no such thing as a "tagged Claims-Set", but a tagged UCCS looks like a "tagged Claims-Set"

**Comment by thomas-fossati** [comment]
OK, I removed the Tag processing because it's redundant.

See https://thomas-fossati.github.io/draft-eat-mt/draft-lundblade-rats-eat-media-type.html#name-eat-types-2
