### ISSUE TITLE
use `+jwt` SSS?

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-eat-mt#14]
IANA's [Structured Syntax Suffixes registry](https://www.iana.org/assignments/media-type-structured-suffix/media-type-structured-suffix.xhtml) has `+jwt`, defined in [RFC8417](https://www.rfc-editor.org/rfc/rfc8417.html#section-7.2) to be _"used indicate that the media type is encoded as a JWT."_

It looks like `application/eat+jwt` could be used instead of `application/eat-jwt`.

**Comment by thomas-fossati** [comment]
Obviously, the next question is: should we register a `+cwt` SSS so we can do `application/eat+cwt` -- and also do the community a favour.

**Comment by laurencelundblade** [comment]
Looked at the various RFC involved and yes, this does seem like the right thing to do, both eat+jwt and eat+cwt. These would replace eat-jwt and eat-cwt.

Thx

**Comment by thomas-fossati** [comment]
Cool, will PR this asap.
