### ISSUE TITLE
Section numbers changed in EAT-13

### ISSUE THREAD

**Issue by laurencelundblade** [thomas-fossati/draft-eat-mt#3]
Not sure how the section number references work here but the EAT-13 draft has significantly different section numbers than -12 and this doc refers to -12 sections.

**Comment by henkbirkholz** [comment]
If there will be more churn, I'd suggest not hunting those inconsistencies too often until the doc moves to IESG. If you thinkn this is relatively stable now, we can pull in -13 in-doc refs.
