### ISSUE TITLE
profile or eat_profile?

### ISSUE THREAD

**Issue by laurencelundblade** [thomas-fossati/draft-eat-mt#4]
This doc refers to both "profile" and "eat_profile". EAT itself uses both terms, the first for the CBOR claim and the second for the JSON claim (because "profile" is already registered in JWT). 

I think we either need to fix EAT so it just uses "eat_profile", or explain the mixing of terms in this document.

**Comment by henkbirkholz** [comment]
If we want that consistency, I agree that this problem ports back to the EAT I-D.

**Comment by laurencelundblade** [comment]
It is the way it is in EAT for a reason. It's not just a sloppy error.

It is to be consistent with all the other EAT claims that don't start with "eat_".

**Comment by thomas-fossati** [comment]
sure, I didn't question that :-) I did :thumbsup: since renaming it to `eat_profile` in CBOR is just cosmetic change, so it seems quite cheap.

**Comment by thomas-fossati** [comment]
@laurencelundblade can this be closed?

**Comment by laurencelundblade** [comment]
EAT is now consistent and uses only "eat_profile". Should this draft name the Optional parameter "eat_profile" to be consistent?

**Comment by thomas-fossati** [comment]
all media type names we define start with `application/eat-`. To me that seems to provide enough context to avoid ambiguity; it also stutters less.  That said, if you are keen on consistency I am not opposed to prepend `eat_`.

**Comment by henkbirkholz** [comment]
eat_profile seems consistent to me.

**Comment by thomas-fossati** [comment]
ok, consistence beats minimalism then :-)
