### ISSUE TITLE
new CoAP option for carrying the profile information

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-eat-mt#6]
We need a way to pass the profile information when using content formats.

A new CoAP option would seem like the natural way to do this.

A generally useful thing could be an option that carries any media type parameters (including profile).

**Comment by thomas-fossati** [comment]
This is now https://datatracker.ietf.org/doc/draft-fossati-core-parametrized-cf/

CoRE interim presentation: https://datatracker.ietf.org/meeting/interim-2022-core-10/materials/slides-interim-2022-core-10-sessa-pramtrzd-pramtrzd-content-format-for-coap-03-00

Minutes: https://datatracker.ietf.org/meeting/interim-2022-core-10/materials/minutes-interim-2022-core-10-202207061600-00

**Comment by thomas-fossati** [comment]
Just noting this is not a blocker.

**Comment by henkbirkholz** [comment]
See: https://datatracker.ietf.org/doc/draft-fossati-core-parametrized-cf/
